name: Deploy Lambda Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'src/lambdas/**'

permissions:
  id-token: write 
  contents: read

jobs:
  deploy-lambdas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # STEP 1: Scan for changed files
      - name: Check for file changes
        uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            find_models:
              - 'src/lambdas/api-find-models.py'
            get_prices:
              - 'src/lambdas/api-get-prices-by-model.py'

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }} 
          aws-region: eu-central-1

      # STEP 2: Deploy find-models Lambda (runs only if its code has changed)
      - name: Update Lambda - Find Models
        if: steps.changes.outputs.find_models == 'true'
        run: |
          cd src/lambdas
          zip find-models.zip api-find-models.py
          aws lambda update-function-code \
            --function-name ${{ vars.PROJECT_NAME }}-find-models \
            --zip-file fileb://find-models.zip
            
      # STEP 3: Deploy get-prices Lambda (runs only if its code has changed)
      - name: Update Lambda - Get Prices
        if: steps.changes.outputs.get_prices == 'true'
        run: |
          cd src/lambdas
          zip get-prices.zip api-get-prices-by-model.py
          aws lambda update-function-code \
            --function-name ${{ vars.PROJECT_NAME }}-get-prices \
            --zip-file fileb://get-prices.zip