name: Deploy Express App to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'src/express/**' # Odpalaj tylko przy zmianach w kodzie aplikacji

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "src/express/*"
          target: "/var/www/app"
          strip_components: 2 # Usuwa foldery "src/express" ze ścieżki na serwerze

      - name: Install dependencies and restart PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/app
            npm install
            # Uruchom aplikację jeśli nie działa, lub zrestartuj jeśli już działa
            pm2 start app.js --name "car-prices-api" || pm2 restart "car-prices-api"
            pm2 save